//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.TrabalhoNB.TextDocs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IA.TrabalhoNB.TextDocs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AO
        ///AOS
        ///AQUELA
        ///AQUELAS
        ///AQUELE
        ///AQUELES
        ///AQUILO
        ///AS
        ///ATE
        ///COM
        ///COMO
        ///DA
        ///DAS
        ///DE
        ///DELA
        ///DELAS
        ///DELE
        ///DELES
        ///DEPOIS
        ///DO
        ///DOS
        ///E
        ///ELA
        ///ELAS
        ///ELE
        ///ELES
        ///EM
        ///ESSA
        ///ESSAS
        ///ESSE
        ///ESSES
        ///EU
        ///ISSO
        ///ISTO
        ///LHE
        ///LHES
        ///MAS
        ///ME
        ///MEU
        ///MEUS
        ///MINHA
        ///MINHAS
        ///NA
        ///NAS
        ///NO
        ///NOS
        ///NOSSA
        ///NOSSAS
        ///NOSSO
        ///NOSSOS
        ///NUM
        ///NUMA
        ///O
        ///OS
        ///OU
        ///PARA
        ///PELA
        ///PELAS
        ///PELO
        ///PELOS
        ///QUAL
        ///QUANDO
        ///QUE
        ///QUEM
        ///SE
        ///SEU
        ///SEUS
        ///SO
        ///SUA
        ///SUAS
        ///TAMBEM
        ///TE
        ///TEU
        ///TEUS
        ///TU
        ///TUA
        ///TUAS
        ///UM
        ///UMA
        ///VOCE
        ///VOCES
        ///VOS
        ///PRA
        ///RT
        ///.
        /// </summary>
        internal static string stopwords {
            get {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }
    }
}
